apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dokuwiki
  namespace: openshift-gitops
spec:
  destination:
    namespace: dokuwiki.
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: dokuwiki
    repoURL: https://github.com/lcolagio/twitch-scribe-rhacm.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
